# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2.1
jobs:
  build:
    working_directory: ~/aoc-2019-kotlin
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
      GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - checkout
      - run:
          name: Run junit tests
          command: ./gradlew test
